on:
  push:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Run tests
        run: |
          set -o pipefail
          xcodebuild test \
            -project Purrl.xcodeproj \
            -scheme Purrl \
            -destination 'platform=macOS,arch=arm64' \
          | xcpretty -c
